numpy


In [7]:
import numpy as np 

In [13]:
np.__version__

'1.26.4'

In [17]:
import sys 
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [25]:
list = [1,2,3,4,5]
list

[1, 2, 3, 4, 5]

converting list to array 

In [31]:
array = np.array(list)
array

array([1, 2, 3, 4, 5])

In [33]:
type(array)

numpy.ndarray

In [35]:
type(list)

list

In [39]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr2 = np.arange(20)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [47]:
type(arr2)

numpy.ndarray

In [55]:
np.arange(0,4)

array([0, 1, 2, 3])

In [57]:
np.arange(20,10)

array([], dtype=int32)

In [59]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [63]:
np.arange(0,10,3)


array([0, 3, 6, 9])

In [67]:
np.arrange(10,30,5,8)

AttributeError: module 'numpy' has no attribute 'arrange'

In [71]:
np.zeros(10)   #with float values 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [94]:
np.zeros(10, dtype=int)  #with float values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [106]:
arr3 = np.zeros((2,5),dtype=int)

In [125]:
arr3 = np.zeros((2,5),dtype=int)
arr3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [133]:
np.ones(3)

array([1., 1., 1.])

In [141]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [143]:
np.ones((3,3),dtype=int) 

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [145]:
np.ones((10,8),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [155]:
import random
random.randint(1,10)

8

In [157]:
np.random.rand(6)

array([0.52032742, 0.02228642, 0.93827072, 0.92299892, 0.3066017 ,
       0.10332132])

In [165]:
np.random.rand((6))

array([0.06999439, 0.5894767 , 0.18535286, 0.48777867, 0.90660957,
       0.23556064])

In [193]:
np.random.randint(1,8)

1

In [195]:
np.random.randint(2,20,4)

array([15, 12,  6,  3])

In [215]:
np.random.randint(0,1)  #it will onlt print 0 

0